version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_USER: ${DB_POS_DEV_USER}
      POSTGRES_PASSWORD: ${DB_POS_DEV_PASSWORD}
      POSTGRES_DB: ${DB_POS_DEV_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POS_DEV_USER} -d ${DB_POS_DEV_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6
    container_name: redis_dev
    ports:
      - "6379:6379"

volumes:
  pgdata:
